import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import {
  ACCENTS,
  Callout,
  ChipRow,
  Prose,
  ReportCover,
  ReportFooter,
  ReportSection,
  ReportShell,
  ReportState,
  TurnBubble,
  formatReportDate,
} from '../components/report'
import { categoryLabel } from '../lib/categories'
import { getAttempts, getDebriefs, type Debrief, type ScenarioAttempt } from '../lib/api'

// One printable report for both halves of Ask & Practice. They are different
// models — an Ask answer is a Debrief, a rehearsal is a ScenarioAttempt — so
// the route carries which kind to load rather than guessing from the id.
const capitalize = (v: string | null) => (v ? v.charAt(0).toUpperCase() + v.slice(1) : null)

export default function AskPracticeExport() {
  const { kind, id } = useParams<{ kind: string; id: string }>()
  const [ask, setAsk] = useState<Debrief | null>(null)
  const [attempt, setAttempt] = useState<ScenarioAttempt | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!id) return
    const load =
      kind === 'practice'
        ? getAttempts().then((all) => setAttempt(all.find((a) => a.id === id) ?? null))
        : getDebriefs({ source: 'ask_tab' }).then((all) => setAsk(all.find((d) => d.id === id) ?? null))
    load.catch(() => {}).finally(() => setLoading(false))
  }, [kind, id])

  if (loading) return <ReportState text="Loading…" />

  const A = ACCENTS
  let n = 0

  if (kind === 'practice') {
    if (!attempt) return <ReportState text="Practice attempt not found." />
    const chat = (attempt.conversation ?? []).slice(2).filter((m) => m.text?.trim())
    return (
      <ReportShell backTo="/coach-chat?tab=practice">
        <ReportCover
          eyebrow="Wivoza · Practice"
          title="A rehearsal"
          meta={formatReportDate(attempt.createdAt)}
          badge={attempt.triedAt ? 'Tried in class' : undefined}
        />
        <div className="mt-5">
          <ChipRow
            // Scenario difficulty is stored lowercase; TryItOut capitalises it
            // for display and the printed chip has to match.
            items={
              [
                categoryLabel(attempt.scenario.category),
                attempt.scenario.gradeBand,
                capitalize(attempt.scenario.difficulty),
              ].filter(Boolean) as string[]
            }
            accent={A.mint}
          />
        </div>

        <ReportSection n={++n} title="The Scenario" blurb="What you were responding to." accent={A.terracotta}>
          <Prose body={attempt.scenario.text} />
        </ReportSection>

        <ReportSection n={++n} title="Your Response" blurb="What you actually said." accent={A.gold}>
          <Prose body={attempt.responseText} />
        </ReportSection>

        {attempt.feedback && (
          <ReportSection n={++n} title="Coaching" blurb="What worked, and the one thing worth changing." accent={A.mint}>
            <Prose body={attempt.feedback} />
          </ReportSection>
        )}

        {attempt.modelResponse && (
          <ReportSection n={++n} title="A Model Response" blurb="To compare against — not to memorise. Yours should sound like you." accent={A.forest}>
            <Prose body={attempt.modelResponse} />
          </ReportSection>
        )}

        {chat.length > 0 && (
          <ReportSection n={++n} title="The Follow-Up" blurb="Where you pushed back or went deeper." accent={A.gold}>
            <div className="flex flex-col gap-3">
              {chat.map((m, i) => (
                <TurnBubble key={i} role={m.role} text={m.text} />
              ))}
            </div>
          </ReportSection>
        )}

        {(attempt.triedAt || attempt.reflectionNote) && (
          <ReportSection n={++n} title="What Happened Next" accent={A.mint}>
            {attempt.triedAt && (
              <p className="text-sm font-semibold text-forest">
                Tried in class on {new Date(attempt.triedAt).toLocaleDateString()}
              </p>
            )}
            {attempt.reflectionNote && <Callout label="My note" body={attempt.reflectionNote} accent={A.mint} />}
          </ReportSection>
        )}
        <ReportFooter note="Generated by Wivoza · wivoza.com · Practice attempts are private. Nobody else sees them." />
      </ReportShell>
    )
  }

  if (!ask) return <ReportState text="Answer not found." />
  const chat = (ask.conversation ?? []).slice(2).filter((m) => m.text?.trim())

  return (
    <ReportShell backTo="/coach-chat">
      <ReportCover
        eyebrow="Wivoza · Ask"
        title="Coaching on a real moment"
        meta={formatReportDate(ask.createdAt)}
        badge={ask.triedAt ? 'Tried in class' : undefined}
      />
      {ask.category && (
        <div className="mt-5">
          <ChipRow items={[categoryLabel(ask.category)]} accent={A.mint} />
        </div>
      )}

      <div className="mt-5 break-inside-avoid rounded-2xl border-l-8 border-gold bg-gold-tint/50 p-6">
        <p className="text-[11px] font-bold uppercase tracking-wide text-terracotta-600">What was going on</p>
        <p className="mt-2 text-base leading-relaxed text-ink">{ask.incidentText}</p>
      </div>

      {ask.feedback && (
        <ReportSection n={++n} title="Coaching" blurb="What actually made this hard." accent={A.terracotta}>
          <Prose body={ask.feedback} />
        </ReportSection>
      )}

      {ask.wordsToTry && (
        <ReportSection n={++n} title="Words to Try" blurb="Actual sentences — adapt them until they sound like you." accent={A.gold}>
          <Prose body={ask.wordsToTry} />
        </ReportSection>
      )}

      {ask.followUp && (
        <ReportSection n={++n} title="One Next Step" blurb="One. Not five." accent={A.mint}>
          <Prose body={ask.followUp} />
        </ReportSection>
      )}

      {chat.length > 0 && (
        <ReportSection n={++n} title="The Follow-Up" accent={A.forest}>
          <div className="flex flex-col gap-3">
            {chat.map((m, i) => (
              <TurnBubble key={i} role={m.role} text={m.text} />
            ))}
          </div>
        </ReportSection>
      )}

      {(ask.triedAt || ask.reflectionNote) && (
        <ReportSection n={++n} title="What Happened Next" accent={A.mint}>
          {ask.triedAt && (
            <p className="text-sm font-semibold text-forest">Tried in class on {new Date(ask.triedAt).toLocaleDateString()}</p>
          )}
          {ask.reflectionNote && <Callout label="My note" body={ask.reflectionNote} accent={A.mint} />}
        </ReportSection>
      )}

      <ReportFooter />
    </ReportShell>
  )
}
