import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import {
  ACCENTS,
  Callout,
  ReportCover,
  ReportFooter,
  ReportSection,
  ReportShell,
  ReportState,
  TurnBubble,
  formatReportDate,
} from '../components/report'
import { getDebriefs, type Debrief } from '../lib/api'

// Printable report for one Talk It Through conversation. There is no
// single-debrief endpoint, so this reads the teacher's own list and finds the
// row — cheap, and avoids adding a server route for a print view.
export default function TalkItThroughExport() {
  const { id } = useParams<{ id: string }>()
  const [debrief, setDebrief] = useState<Debrief | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!id) return
    getDebriefs({ source: 'talk_to_me' })
      .then((all) => setDebrief(all.find((d) => d.id === id) ?? null))
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [id])

  if (loading) return <ReportState text="Loading…" />
  if (!debrief) return <ReportState text="Conversation not found." />

  const A = ACCENTS
  const takeaway = debrief.talkTakeaway
  const turns = (debrief.conversation ?? []).filter((m) => m.text?.trim())
  let n = 0

  return (
    <ReportShell backTo="/talk-to-me">
      <ReportCover
        eyebrow="Wivoza · Talk It Through"
        title="What you talked through"
        meta={formatReportDate(debrief.createdAt)}
        badge={debrief.triedAt ? 'Tried in class' : undefined}
      />

      <div className="mt-5 break-inside-avoid rounded-2xl border-l-8 border-gold bg-gold-tint/50 p-6">
        <p className="text-[11px] font-bold uppercase tracking-wide text-terracotta-600">How it started</p>
        <p className="mt-2 text-base leading-relaxed text-ink">{debrief.incidentText}</p>
      </div>

      {takeaway && (
        <ReportSection n={++n} title="Your Takeaway" blurb="The three things this conversation ended with." accent={A.terracotta}>
          <Callout label="What we explored" body={takeaway.explored} accent={A.mint} />
          <Callout label="What I'll try" body={takeaway.tryNext} accent={A.terracotta} />
          <Callout label="What I'll notice" body={takeaway.notice} accent={A.gold} />
        </ReportSection>
      )}

      {turns.length > 0 && (
        <ReportSection n={++n} title="The Conversation" blurb="Everything that was said, in order." accent={A.forest}>
          <div className="flex flex-col gap-3">
            {turns.map((m, i) => (
              <TurnBubble key={i} role={m.role} text={m.text} />
            ))}
          </div>
        </ReportSection>
      )}

      {(debrief.triedAt || debrief.reflectionNote) && (
        <ReportSection n={++n} title="What Happened Next" blurb="The part that turns a conversation into a change." accent={A.mint}>
          {debrief.triedAt && (
            <p className="text-sm font-semibold text-forest">
              Tried in class on {new Date(debrief.triedAt).toLocaleDateString()}
            </p>
          )}
          {debrief.reflectionNote && <Callout label="My note" body={debrief.reflectionNote} accent={A.mint} />}
        </ReportSection>
      )}

      <ReportFooter note="Generated by Wivoza · wivoza.com · Your voice was never saved — only this text." />
    </ReportShell>
  )
}
